version: '3.8'

services:
  monitor:
    build: .
    container_name: auditmatrix-monitor
    command: python main.py --read-from-start
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_SOURCE_PATH=logs/sistema.log
      - AUDIT_TEXT_PATH=logs/auditoria.txt
      - DEBUG=true
    restart: unless-stopped
